server {
    listen 6000; #0 255
    host 127.0.0.1;
    server_name    .com;

    root ../www;

    error_page 404 ./www/error/404.html;
    error_page 500 ./www/error/500.html;

    client_max_body_size -01;

}